### ISSUE TITLE
Bug/Regression | Disable automatic translation of inlineEditable fields

### ISSUE THREAD

**Issue by MiauzGenau** [sitegeist/Sitegeist.LostInTranslation#47]
As stated in #7, it is currently not possible to disable translations for inlineEditable properties.

```
'Neos.Neos:Document':
  properties:
    uriPathSegment:
      options:
        automaticTranslation: false
```
Does not disable the automatic translations for this property, as it is set to `inlineEditable: true`.
