### ISSUE TITLE
Reimplement sync for Neos 9

### ISSUE THREAD

**Issue by mficzel** [sitegeist/Sitegeist.LostInTranslation#54]
After the initial release for Neos 9  the sync feature should be restored. Different to the old implementation it should configure explicitly which workspace / language should be translated to which workspace / language.

Possible config syntax could look like this:

```yaml
Sitegeist:
  LostInTranslation:    
    nodeTranslation:
      synchronization:
           # en -> es
           - sourceWorkspaceName: live
              sourceLanguage: en
              targetWorkspaceName: es-review
              targetLanguage: es
           # en -> de 
           - sourceWorkspaceName: live
              sourceLanguage: en
              targetWorkspaceName: de-review
              targetLanguage: de
```

Also the new feature should probably work with a jobqueue as it will probably work onPublish and has to handle lots of events at once.

**Comment by JamesAlias** [comment]
FYI: I'm working on a draft for this here: https://github.com/sandstorm/Sitegeist.LostInTranslation/tree/retranslation-synchronisation

We use it in a project and are cleaning up some rough edges before opening a PR.

**Comment by Bolkun** [comment]
Hallo @JamesAlias I trying to use your forked package. Synchronisation works, but it does not translate from de to en_US. Could it be a problem by using en_US instead of en?

```
Sitegeist:
  LostInTranslation:
    nodeTranslation:
      synchronization:
        - sourceWorkspaceName: live
          sourceDimension: de
          targetWorkspaceName: live
          targetDimension: en_US
          scope: Document
          onSourceRemoval: remove-target
          onSourceTagging: sync-to-target
    DeepLApi:
      authenticationKey: '%env:DEEPL_KEY%'

Neos:
  ContentRepositoryRegistry:
    contentRepositories:
      default:
        contentDimensions:
          language:
            values:
              en_US:
                referenceLanguage: de

Neos:
  Neos:
    routing:
      supportEmptySegmentForDimensions: true
    sites:
      '*':
        contentDimensions:
          defaultDimensionSpacePoint:
            language: de
          resolver:
            factoryClassName: Neos\Neos\FrontendRouting\DimensionResolution\Resolver\UriPathResolverFactory
            options:
              segments:
                -
                  dimensionIdentifier: language
                  dimensionValueMapping:
                    de: ''
                    en_US: en
  ContentRepositoryRegistry:
    contentRepositories:
      default:
        contentDimensions:
          language:
            label: 'Scdd.Website:Main:contentDimensions.language'
            icon: language
            default: 'de'
            values:
              de:
                label: Deutsch
              en_US:
                label: English
```
