### ISSUE TITLE
Disable automatic translation on inlineEditable fields

### ISSUE THREAD

**Issue by rolandschuetz** [sitegeist/Sitegeist.LostInTranslation#7]
> Felix will take a look at this issue

As an integrator, I want to disable automatic translation on an inline editable property. Example:

```yaml
address:
  type: string
  ui:
    inlineEditable: true
    inline:
      editorOptions:
        placeholder: 'Adresse hier eingeben...'
  options:
    automaticTranslation: false
```
